language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-minimizr' ]; then cd .. && eval "mv $currentfolder generator-minimizr" && cd generator-minimizr; fi

