language: node_js
node_js:
  - '0.8'
  - '0.10'

before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-minimizr' ]; then cd .. && eval "mv $currentfolder generator-minimizr" && cd generator-minimizr; fi
  - npm install -g yo
  - npm link

script:
  - yo minimizr
  - grunt

notifications:
  emails:
    - abdonwww@gmail.com
  on_success: always # default: change
  on_failure: always
